### ISSUE TITLE
[FEAT] OTR 9차 ISSUE🌈

### ISSUE THREAD

**Issue by HeesuSoh** [Likelion-at-SMWU-10th/OTR_client#16]
## 📌  Feature Issue

7일 문답페이지 완성하겠습니다. 

## 📝  To-do

- [ ] 7일 문답페이지 첫 화면 변경
- [ ] 1일차 질문 페이지 제작 
- [ ] 2일차 질문 페이지 제작
