### ISSUE TITLE
[FEAT] OTR 5차 ISSUE🌈

### ISSUE THREAD

**Issue by HeesuSoh** [Likelion-at-SMWU-10th/OTR_client#9]
## 📌  Feature Issue

React Router 사용 관련해서 다시 셋팅이 필요해 작업 진행하겠슴다

## 📝  To-do

- [x] ReactRouterDOM설치
- [x] index.jsx 파일 수정
- [x] App.jsx 파일 수정 -> 앞으로 이 파일은 ReactRouter 경로를 지정해주기 위해서만 사용
- [x] Pages 폴더 생성 -> 이 폴더에는 앞으로 연결해줄 페이지들을 관리
- [x] Pages 폴더 안에 연결 필요한 페이지들 넣기
- [x] Pages 폴더 안에 component 폴더 옮겨주기 -> 같은 폴더에 위치하지 않으면 import 할때 오류 발생!
